In [2]:
import pandas as pd
from pathlib import Path

In [3]:
exercise_path = Path("/Users/abelluc/FAUbox/DigiKolleg/BPOS/Exercise/WS23_24_Results")

In [26]:
# Read in the data

In [37]:
assignment_list = ["Assignment_1", "Assignment_2", "Assignment_3", "Assignment_4", "Assignment_5"]

In [118]:
total = {}

In [119]:
for assignment in assignment_list:
    df = pd.read_excel(exercise_path / f"{assignment}.xlsx")

    print(assignment)

    try:
        assignment_df = df[["Login", 1]]
    except KeyError:
        assignment_df = df[["Login", "Test Results in Marks"]]
    assignment_df.columns = ["idm", "passed"]
    assignment_df.set_index("idm", inplace=True)
    assignment_df.replace("passed", "Passed", inplace=True)

    assignment_df["passed"] = assignment_df["passed"] == "Passed"

    total[assignment] = assignment_df

Assignment_1
Assignment_2
Assignment_3
Assignment_4
Assignment_5

/var/folders/3_/6bdchgy93zggkgq8kw8gyssr0000gn/T/ipykernel_89558/3589291104.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assignment_df["passed"] = assignment_df["passed"] == ("Passed" or "passed")
/var/folders/3_/6bdchgy93zggkgq8kw8gyssr0000gn/T/ipykernel_89558/3589291104.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assignment_df["passed"] = assignment_df["passed"] == ("Passed" or "passed")
/var/folders/3_/6bdchgy93zggkgq8kw8gyssr0000gn/T/ipykernel_89558/3589291104.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assignment_df["passed"] = assignment_df["passed"] == ("Passed" or "passed")
/var/folders/3_/6bdchgy93zggkgq8kw8gyssr0000gn/T/ipykernel_89558/3589291104.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assignment_df["passed"] = assignment_df["passed"] == ("Passed" or "passed")
/var/folders/3_/6bdchgy93zggkgq8kw8gyssr0000gn/T/ipykernel_89558/3589291104.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assignment_df["passed"] = assignment_df["passed"] == ("Passed" or "passed")

In [141]:
df = pd.read_excel(exercise_path / "Assignment_2.xlsx")

In [143]:
df
assignment_df = df[["Login", "Test Results in Marks"]]
assignment_df.columns = ["idm", "passed"]
assignment_df.set_index("idm", inplace=True)
assignment_df.replace("passed", "Passed", inplace=True)
assignment_df["passed"] = assignment_df["passed"] == "Passed"


assignment_df

/var/folders/3_/6bdchgy93zggkgq8kw8gyssr0000gn/T/ipykernel_89558/886714861.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  assignment_df["passed"] = assignment_df["passed"] == "Passed"

          passed
idm
up38ijep   False
NaN        False
yz45eryf   False
NaN        False
we15jori   False
NaN        False
za67salo   False
NaN        False
vy30goxy   False
NaN        False
ac13atok   False
NaN        False
sa58juwu   False
NaN        False
an46ykim   False
NaN        False
nu84byna   False
NaN        False
bi30lojy   False
NaN        False
al96amyg   False
NaN        False
ok62ihoc   False
NaN        False
we70xebi   False
NaN        False
fy02myxa   False
NaN        False
lo82weta   False
NaN        False
se67myvy   False
NaN        False
ga20lydi   False
NaN        False
uz45uhal   False
NaN        False
wa94kejo   False
NaN        False
ys47ojus   False
NaN        False
yh07ajaw   False
NaN        False
qo24gufe   False
NaN        False
ga45wapo   False
NaN        False
uh87yhit   False

In [120]:
# convert dict to dataframe
total_df = pd.concat(total, axis=0)

In [121]:
total_df.index.names = ["assignment", "idm"]
total_df = total_df.reset_index()
total_df.dropna(how="any", inplace=True)
total_df = total_df.set_index(["idm", "assignment"])

In [122]:
total_df.dropna(how="any")

                        passed
idm       assignment
luca.abel Assignment_1   False
yz45eryf  Assignment_1   False
ib35olyr  Assignment_1   False
we15jori  Assignment_1    True
za67salo  Assignment_1    True
...                        ...
lo82weta  Assignment_5   False
se67myvy  Assignment_5   False
yt60ubym  Assignment_5   False
yh07ajaw  Assignment_5   False
qo24gufe  Assignment_5   False

[116 rows x 1 columns]

In [123]:
total_df.sort_index(inplace=True)

In [124]:
total_df.unstack("assignment")

                 passed
assignment Assignment_1 Assignment_2 Assignment_3 Assignment_4 Assignment_5
idm
ac13atok           True        False        False         True        False
al96amyg            NaN        False          NaN          NaN          NaN
an46ykim           True        False        False         True        False
ax73aqur          False          NaN          NaN          NaN          NaN
bi30lojy           True        False        False         True        False
fi89bipe            NaN          NaN        False          NaN        False
fu40panu          False          NaN        False        False          NaN
fy02myxa           True        False          NaN          NaN          NaN
ga20lydi           True        False          NaN          NaN          NaN
ga45wapo           True        False          NaN          NaN          NaN
go63gaxo           True          NaN        False          NaN        False
hu59vore           True          NaN        False          NaN          NaN
ib35olyr          False          NaN          NaN        False          NaN
je18kuta          False          NaN          NaN          NaN          NaN
le79piqy          False          NaN        False          NaN          NaN
lo82weta          False        False        False          NaN        False
luca.abel         False          NaN        False          NaN          NaN
ni24bere          False          NaN          NaN          NaN          NaN
nu84byna           True        False        False         True        False
ok62ihoc           True        False        False         True        False
qo24gufe           True        False        False         True        False
ry66cyfu          False          NaN          NaN          NaN          NaN
sa58juwu           True        False        False        False          NaN
se67myvy           True        False        False         True        False
uh87yhit           True        False        False         True          NaN
up38ijep            NaN        False        False        False          NaN
uw34esul          False          NaN          NaN          NaN          NaN
uz45uhal           True        False        False         True          NaN
ve76kyxi          False          NaN          NaN          NaN          NaN
vy30goxy           True        False        False         True        False
wa94kejo          False        False          NaN          NaN          NaN
we15jori           True        False        False         True        False
we70xebi           True        False        False         True        False
wo16keno           True          NaN          NaN          NaN          NaN
xo62nyru          False          NaN          NaN          NaN          NaN
yh07ajaw           True        False        False        False        False
ys47ojus           True        False          NaN          NaN          NaN
yt60ubym          False          NaN          NaN          NaN        False
yz45eryf          False        False          NaN          NaN          NaN
za67salo           True        False          NaN          NaN        False