In [2]:
import pandas as pd

from pathlib import Path

### Load Scores

In [4]:
exercise_path = Path("course_directory/ads_exercise")
output_path = Path("total_score")

In [7]:
scores = pd.read_csv(exercise_path.joinpath("grades.csv"))
scores.head()

,assignment,duedate,timestamp,student_id,last_name,first_name,email,raw_score,late_submission_penalty,score,max_score
0,04_python_basics_III,NaN,NaN,theresanadler,NaN,NaN,NaN,0.0,0.0,0.0,10.0
1,04_python_basics_III,NaN,NaN,moestenfau,NaN,NaN,NaN,0.0,0.0,0.0,10.0
2,04_python_basics_III,NaN,NaN,lucaabel,NaN,NaN,NaN,7.0,0.0,7.0,10.0
3,04_python_basics_III,NaN,NaN,moesten,NaN,NaN,NaN,0.0,0.0,0.0,10.0
4,04_python_basics_III,NaN,NaN,AhmedSofan10,NaN,NaN,NaN,0.0,0.0,0.0,10.0

In [38]:
score_long = scores.set_index(["student_id", "assignment"]).sort_index()
score_long

                                   duedate  timestamp  last_name  first_name  \
student_id   assignment
AhmedSofan10 04_python_basics_III      NaN        NaN        NaN         NaN
             ads_assignment_1          NaN        NaN        NaN         NaN
             ads_assignment_2          NaN        NaN        NaN         NaN
             ads_assignment_3          NaN        NaN        NaN         NaN
ArefehRh     04_python_basics_III      NaN        NaN        NaN         NaN
...                                    ...        ...        ...         ...
youssafB     ads_assignment_3          NaN        NaN        NaN         NaN
yp69ejot     04_python_basics_III      NaN        NaN        NaN         NaN
             ads_assignment_1          NaN        NaN        NaN         NaN
             ads_assignment_2          NaN        NaN        NaN         NaN
             ads_assignment_3          NaN        NaN        NaN         NaN

                                   email  raw_score  late_submission_penalty  \
student_id   assignment
AhmedSofan10 04_python_basics_III    NaN        0.0                      0.0
             ads_assignment_1        NaN        1.0                      0.0
             ads_assignment_2        NaN        0.0                      0.0
             ads_assignment_3        NaN        0.0                      0.0
ArefehRh     04_python_basics_III    NaN        0.0                      0.0
...                                  ...        ...                      ...
youssafB     ads_assignment_3        NaN        0.0                      0.0
yp69ejot     04_python_basics_III    NaN        0.0                      0.0
             ads_assignment_1        NaN        1.0                      0.0
             ads_assignment_2        NaN        8.0                      0.0
             ads_assignment_3        NaN        0.0                      0.0

                                   score  max_score
student_id   assignment
AhmedSofan10 04_python_basics_III    0.0       10.0
             ads_assignment_1        1.0        1.0
             ads_assignment_2        0.0        8.0
             ads_assignment_3        0.0       10.0
ArefehRh     04_python_basics_III    0.0       10.0
...                                  ...        ...
youssafB     ads_assignment_3        0.0       10.0
yp69ejot     04_python_basics_III    0.0       10.0
             ads_assignment_1        1.0        1.0
             ads_assignment_2        8.0        8.0
             ads_assignment_3        0.0       10.0

[248 rows x 9 columns]

In [39]:
sum_points = score_long["score"].unstack("assignment").sum(axis=1)
sum_points

student_id
AhmedSofan10    1.0
ArefehRh        7.0
Ashikluffy      1.0
Chamutalcast    9.0
Dan-github16    1.0
               ...
viranya31       1.0
vv88alias       9.0
xindiyu         9.0
youssafB        0.0
yp69ejot        9.0
Length: 62, dtype: float64

In [48]:
max_score = score_long.xs(score_long.index[0][0], level="student_id")["max_score"].sum() # select the first student
max_score

29.0

In [60]:
# set this manually, when the score is not right
max_score = 9.0

In [61]:
percentage = (sum_points / max_score) *100
percentage

student_id
AhmedSofan10     11.111111
ArefehRh         77.777778
Ashikluffy       11.111111
Chamutalcast    100.000000
Dan-github16     11.111111
                   ...
viranya31        11.111111
vv88alias       100.000000
xindiyu         100.000000
youssafB          0.000000
yp69ejot        100.000000
Length: 62, dtype: float64

In [65]:
import time

semester = "SoSe_23"

# export csv
timestr = time.strftime("%Y%m%d-%H%M%S")
percentage.to_csv(output_path.joinpath(semester+"-"+timestr+".csv"))