In [1]:
import pandas as pd
from pathlib import Path
import glob
import os
import time

### Extract student identifiers from StudOn export for import in GitHub Classroom

In [ ]:
# change this to the current semester
semester = "SoSe_26"

In [4]:
studon_path = Path("studon_export")
roster_path = Path("student_roster")

In [5]:
list_of_files = glob.glob("studon_export/*.csv")
latest_export = max(list_of_files, key=os.path.getctime) # get the latest export
latest_export

'studon_export/2025_04_28_11-141745831666_member_export_8679888.csv'

In [6]:
roster_df = pd.read_csv(latest_export)
roster_df.head()

,Role / Status,Login/register,Message,Last Name,First Name,Login,E-Mail,Matriculation number,Degree program data
0,Member,"2. Apr 2025, 14:39",NaN,Abdelmaguid,Elsaeed Ahmed Elsaeed Ali,mo76nery,elsaeed.a.abdelmaguid@fau.de,23650382,In summer 2025 (Vollzeitstudium): / Data Scie...
1,Member,"14. Apr 2025, 18:47",NaN,Adil,Muhammad,lo72myqi,sardar.adil@fau.de,23477167,In summer 2025 (Vollzeitstudium): / Data Scie...
2,Member,"10. Mar 2025, 14:48",NaN,Ahmed,Hasnain,aq89opob,hasnain.ahmed@fau.de,23129180,In summer 2025 (Vollzeitstudium): / Data Scie...
3,Member,"12. Mar 2025, 21:52",NaN,Ahsan,Mherub,pa57rapa,mherub.ahsan@fau.de,23457144,In summer 2025 (Vollzeitstudium): / Data Scie...
4,Member,"14. Apr 2025, 22:42",NaN,Akdoğan,Melis,no73widi,melis.akdogan@fau.de,23614846,In summer 2025 (Vollzeitstudium): / Informati...

In [7]:
idm_identifiers = roster_df["Login"]
idm_identifiers

0      mo76nery
1      lo72myqi
2      aq89opob
3      pa57rapa
4      no73widi
         ...
237    je81paze
238    ec78ihob
239    if64azoc
240    xo25govo
241    im87ixel
Name: Login, Length: 242, dtype: object

In [9]:
# export csv
timestr = time.strftime("%Y%m%d-%H%M%S")
idm_identifiers.to_csv(roster_path.joinpath(semester+"-"+timestr), index=False, header=False)

### Diff from last and current

In [10]:
list_of_files.sort(key=os.path.getctime)
#last_filename = list_of_files[-2]
last_filename

'studon_export/2024_04_12_13-391712921986_member_export_7692618.csv'

In [11]:
last = pd.read_csv(last_filename)
last

,Role / Status,Registration/First access,Message,Last Name,First Name,Login,E-Mail,Matriculation number
0,Member,"23. Mar 2024, 03:18",NaN,Alam,KM Rashedul,pi44ditu,rashedul.alam@fau.de,23008271
1,Member,"30. Mar 2024, 10:14",NaN,Aschoff,Moritz,le49xeof,moritz.aschoff@fau.de,22952401
2,Member,"9. Mar 2024, 11:58",NaN,Baghnavi,Mahdieh,vi92tyju,mahdieh.saina.baghnavi@fau.de,22954021
3,Member,"8. Mar 2024, 10:09",NaN,Bastani,Parisa,ze30qyse,parisa.bastani@fau.de,23234460
4,Member,"6. Apr 2024, 20:10",NaN,Beblik,Konstantin,eh92yjoq,konstantin.beblik@fau.de,22562720
...,...,...,...,...,...,...,...,...
81,Member,"12. Apr 2024, 08:08",NaN,Wang,Tianyi,uh41elaj,tianyi.tw.wang@fau.de,23338886
82,Member,"30. Mar 2024, 18:28",NaN,Wiemann,Hannah-Marie,ir21uqow,hannah-marie.wiemann@fau.de,23488119
83,Member,"28. Mar 2024, 17:57",NaN,Yarlagadda,Tejaswi,ug36eqom,tejaswi.y.yarlagadda@fau.de,23227772
84,Member,"13. Mar 2024, 21:01",NaN,Zahin,Farhan,qa23jora,farhan.zahin@fau.de,23032321
85,Member,"5. Mar 2024, 10:53",NaN,Zhong,Sheng,if64azoc,sheng.zhong@fau.de,23067142

In [12]:
idm_identifiers_last = last["Login"]
idm_identifiers_last

0     pi44ditu
1     le49xeof
2     vi92tyju
3     ze30qyse
4     eh92yjoq
        ...
81    uh41elaj
82    ir21uqow
83    ug36eqom
84    qa23jora
85    if64azoc
Name: Login, Length: 86, dtype: object

In [13]:
# get only the new students
new_students = idm_identifiers[~idm_identifiers.isin(idm_identifiers_last)]

In [14]:
new_students

5     za41xuki
6     to10fape
20    ty02muwa
25    yk44obyb
49    wi93xyle
55    aq01ukax
58    es06usad
61    yr92osyb
69    ys42ibuq
75    ky38hefe
79    ur55eryj
96    wi19puqa
Name: Login, dtype: object

In [16]:
# export csv
timestr = time.strftime("%Y%m%d-%H%M%S")
new_students.to_csv(roster_path.joinpath("updates").joinpath(semester+"-"+timestr), index=False, header=False)