In [10]:
import pandas as pd
from pathlib import Path
import glob
import os
import time

### Extract student identifiers from StudOn export for import in GitHub Classroom

In [11]:
# change this to the current semester
semester = "SoSe_24"

In [12]:
studon_path = Path("studon_export")
roster_path = Path("student_roster")

In [13]:
list_of_files = glob.glob("studon_export/*.csv")
latest_export = max(list_of_files, key=os.path.getctime) # get the latest export
latest_export

'studon_export/2024_04_15_10-011713168067_member_export_7692618.csv'

In [14]:
roster_df = pd.read_csv(latest_export)
roster_df.head()

,Role / Status,Registration/First access,Message,Last Name,First Name,Login,E-Mail,Matriculation number
0,Member,"23. Mar 2024, 03:18",NaN,Alam,KM Rashedul,pi44ditu,rashedul.alam@fau.de,23008271
1,Member,"30. Mar 2024, 10:14",NaN,Aschoff,Moritz,le49xeof,moritz.aschoff@fau.de,22952401
2,Member,"9. Mar 2024, 11:58",NaN,Baghnavi,Mahdieh,vi92tyju,mahdieh.saina.baghnavi@fau.de,22954021
3,Member,"8. Mar 2024, 10:09",NaN,Bastani,Parisa,ze30qyse,parisa.bastani@fau.de,23234460
4,Member,"6. Apr 2024, 20:10",NaN,Beblik,Konstantin,eh92yjoq,konstantin.beblik@fau.de,22562720

In [15]:
idm_identifiers = roster_df["Login"]
idm_identifiers

0     pi44ditu
1     le49xeof
2     vi92tyju
3     ze30qyse
4     eh92yjoq
        ...
92    ir21uqow
93    ug36eqom
94    qa23jora
95    if64azoc
96    wi19puqa
Name: Login, Length: 97, dtype: object

In [16]:
# export csv
timestr = time.strftime("%Y%m%d-%H%M%S")
idm_identifiers.to_csv(roster_path.joinpath(semester+"-"+timestr), index=False, header=False)

### Diff from last and current

In [17]:
list_of_files.sort(key=os.path.getctime)
last_filename = list_of_files[-2]
last_filename

'studon_export/2024_04_12_13-391712921986_member_export_7692618.csv'

In [12]:
last = pd.read_csv(last_filename)
last

   Rolle/Status Anmeldung/Erstzugriff  Nachricht Benutzername
0      Mitglied   12. Apr 2023, 12:35        NaN     id82ilyx
1      Mitglied   05. Apr 2023, 05:24        NaN     ty28vipo
2      Mitglied   08. Apr 2023, 17:57        NaN     qe72syka
3      Mitglied   05. Apr 2023, 23:52        NaN     ed10ipan
4      Mitglied   28. Mär 2023, 15:17        NaN     yc84icis
..          ...                   ...        ...          ...
69     Mitglied   29. Mär 2023, 13:20        NaN     ji91cigo
70     Mitglied   29. Mär 2023, 10:26        NaN     if80ajil
71     Mitglied   28. Mär 2023, 13:42        NaN     xe61xija
72     Mitglied   16. Apr 2023, 08:11        NaN     vo28hudo
73     Mitglied   27. Mär 2023, 19:51        NaN     if64azoc

[74 rows x 4 columns]

In [14]:
idm_identifiers_last = last["Benutzername"]
idm_identifiers_last

0     id82ilyx
1     ty28vipo
2     qe72syka
3     ed10ipan
4     yc84icis
        ...
69    ji91cigo
70    if80ajil
71    xe61xija
72    vo28hudo
73    if64azoc
Name: Benutzername, Length: 74, dtype: object